[build]
builder = "NIXPACKS"
buildCommand = "npm install --production=false"

[deploy]
startCommand = "npm run server:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_VERSION = "20"
